FROM node:20

WORKDIR /var/www/html

RUN chown -R node:node /var/www/html /home/node

USER node

COPY --chown=node:node src/package*.json ./
RUN npm install

COPY --chown=node:node src/ ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
